const DEFAULT_PAGE = 1;
const PAGE_SIZE = {
  6: 4,
  10: 10,
};
const DEFAULT_BOOKS_PER_PAGE = 6;
const DEFAULT_ARTICLES_PER_PAGE = 9;
const DEFAULT_LATEST_ARTICLES_NUMBER = 3;

export {
  DEFAULT_PAGE,
  PAGE_SIZE,
  DEFAULT_BOOKS_PER_PAGE,
  DEFAULT_ARTICLES_PER_PAGE,
  DEFAULT_LATEST_ARTICLES_NUMBER,
};
